Repository pylover/bddrest, pull requests merged in 2019-02, with the labels that each got.

#49 Adding CURL class
  bddrest/documentary/curl.py
  bddrest/documentary/documenter.py
  bddrest/tests/test_cli.py
  bddrest/tests/test_curl.py
  bddrest/tests/test_documentary.py
Labels: feature

#50 v2.2.0
  bddrest/__init__.py
Labels: deployment

#51 Migrated to easycli
  bddrest/.cli.py.swo
  bddrest/cli.py
  bddrest/cli/__init__.py
  bddrest/cli/launchers.py
  bddrest/documentary/__init__.py
  setup.py
Labels: feature

#55 Ignoring failing tests until resolving the problem
  bddrest/tests/_test_cli.py
Labels: bug

#57 Resolving the warnings
  bddrest/response.py
  bddrest/specification/call.py
Labels: enhancement

#58 Fixed a bug on the CURL creation
  bddrest/documentary/curl.py
  bddrest/tests/test_cli.py
Labels: bug

#41 Fixed a bug on the auto document related to the multipart
  bddrest/documentary/documenter.py
  bddrest/tests/test_multipart_form.py
Labels: bug

#62 Fixed a bug on the CURL creation related to multipart
  bddrest/cli.py
  bddrest/documentary/curl.py
  bddrest/tests/test_cli.py
  bddrest/tests/test_multipart_form.py
  setup.py
Labels: bug
